language: node_js
node_js:
- 4.1.1
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: RADjPRVMxtZo0NF2Le7Zf5rUGA4tk++dwmA4ks4HvkdGKdLQPYbMStsYn5kFD8yIfH+mzp3NxnP4m7lDgawozbYLW/BPuQR+yezxADb4YRvftBS/R916qFJ9OknBZxVVFEOg4VkX6NnWMSHlWzQq0YQrkqq9BP6lPh+mqxrAOVk=
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: XqOJXEqMzLY+RE/b5qYJGgjXDXhlpgSuLynI0xOoy99fSkZd4fpcWE0ZNSHmJWaouKgI8Yp2kkQY0IBY0u/C3WLO+KOaUovHQ8bjxbicumVKnXr7nyr6SF263DdgMQrlJh0mp/71b43j9OZ3wHf2FGE5094FWeh/CEdzY+ERfWw=
